name: yasur_ml
channels:
  - conda-forge
  - defaults
dependencies:
  - black
  - cartopy
  - gdal
  - gmt
  - ipython
  - isort
  - obspy
  - pip
  - pyarrow
  - pygmt
  - rasterio
  - scikit-learn
  - tsfresh
  - utm
  - xarray
  - pip:
      - --editable ${HOME}/work/python_util
      - --editable ${HOME}/repos/waveform_collection
      - --editable ${HOME}/repos/rtm
      - --editable ${HOME}/work/yasur_ml

# Subcrater S and subcrater N colors, taken from first two entries in "New Tableau 10",
# see https://www.tableau.com/about/blog/2016/7/colors-upgrade-tableau-10-56782
variables:
  SUBCRATER_S: '#4e79a7'
  SUBCRATER_N: '#f28e2b'
