name: yasur_ml
channels:
  - conda-forge
  - defaults
dependencies:
  - black
  - cartopy
  - cffi=1.14.4  # So MacOSX backend works with hack
  - colorcet
  - gdal
  - gmt
  - ipython
  - isort
  - obspy
  - pip
  - pygmt
  - pyqt  # For using Qt5Agg backend with Matplotlib
  - rasterio
  - scikit-learn
  - tsfresh
  - utm
  - xarray
  - pip:
      - --editable ${HOME}/work/python_util
      - --editable ${HOME}/repos/waveform_collection
      - --editable ${HOME}/repos/rtm
