name: yasur_ml
channels:
  - conda-forge
  - defaults
  - conda-forge/label/dev
dependencies:
  - black
  - cartopy
  - colorcet
  - gdal
  - gmt=6.2.*  # Otherwise station_map.py crashes
  - ipython
  - isort
  - obspy
  - pip
  - pygmt
  - rasterio
  - scikit-learn
  - tsfresh
  - utm
  - xarray
  - pip:
      - --editable ${HOME}/work/python_util
      - --editable ${HOME}/repos/waveform_collection
      - --editable ${HOME}/repos/rtm
