name: yasur_ml
channels:
  - conda-forge
  - defaults
dependencies:
  - black
  - cartopy
  - gdal
  - ipython
  - isort
  - numpy<=1.21  # To fix "Numba needs NumPy 1.21 or less" TSFRESH ImportError
  - obspy
  - pip
  - pyarrow
  - pygmt
  - rasterio
  - scikit-learn
  - tsfresh
  - utm
  - xarray
  - pip:
      - git+https://github.com/uafgeotools/waveform_collection.git
      - git+https://github.com/uafgeotools/rtm.git
      - --editable .

# Subcrater S and subcrater N colors, taken from first two entries in "New Tableau 10",
# see https://www.tableau.com/about/blog/2016/7/colors-upgrade-tableau-10-56782
variables:
  SUBCRATER_S: '#4e79a7'
  SUBCRATER_N: '#f28e2b'
